version: '3.7'

networks:
  zoonetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8

services:
  zookeeper1:
    image: bitnami/zookeeper:latest
    hostname: zookeeper1
    networks:
      zoonetwork:
        ipv4_address: 10.50.0.1
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - ./data/zookeeper:/bitnami/zookeeper

  zoonavigator:
    image: elkozmon/zoonavigator:latest
    networks:
      zoonetwork:
        ipv4_address: 10.50.1.1
    ports:
      - 8000:8000
    environment:
      HTTP_PORT: 8000
      AUTO_CONNECT_CONNECTION_STRING: zookeeper1:2181